---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-env-secret
  namespace: grafana
spec:
  encryptedData:
    GF_AUTH_AZUREAD_CLIENT_SECRET: AgDIlf43BFCUewx+MP75OxT4vkqknzci6SqcGLEKb3LnFfSfQeNi0ep7QkC3Zsl+aRN7tQrcdWqQy+LAYh1sMzLnete1N6cyzdN0nvuj66YchMbRSYvLH/+Ugd1wH8oIM0fY3fBIC/X0CZfjZK2r5C8l/SIrO9OYCbboaddTP/zjCh+3K75Quxi4bsFmLZIs+ItiZz0HmcSCMXqciLGydfvouB5NVOTJ9ffQINHCWlTZAk2HQNVfsqahPAfC2L+aDwKcfEcddfY5ubWE1dWWXK6pjKkO2rUASyl1UTBPyaopnKel0BMLWRs6TET2cqoq9R9YTF8/cEqQLNKhXLl1SkQzfo3Lgli3bzyHX75dH3fIdCm93Hk9s1JFUY+gRRAk0NXQl4GauNyjHDf1aME496hhtD8dSxB0mAxTlqRVV8tKJJ3NXRW4c6jTtv6s1NHlvbCpuEkNeaEzwllQtzqnCJsCK9fuRayARLfScv97PMcvALA1EW7DRx8TaSzzenUPWxjM5FTlBJ7XFDYQEOP66XFqonXJS280QhEJA2QFaoOg4q17/mDT5U8MyajqjMAZxBSGmswytfbLCbYnAiegKwgPSojRrU5hOyqkiLMk3oZ7QPHNhZyXJHZzhZQx+GJ8xC0o6qTGgVxpvtU1YNS/ilepZ7mY2bTD9vzP2rVRIFGw50vWt97d1qxwgV6KjaWufK5bC/1FymskPgA+heILffZQUGBglSC1zOLX5/oVm+a20uCSAh+PrbKu
  template:
    metadata:
      creationTimestamp: null
      name: grafana-env-secret
      namespace: grafana
