apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-redis-secret
  namespace: deeppharmgraph
spec:
  encryptedData:
    password: AgC8OrhNQQ8jlF1inlEcLwXhFsSZv94SKDFtbZ9YanB7AcZvnwpa8X2+SIHV8F9+SjcAeAc26Wd6lfznclJdPzrKIB0d18TLwPFQGxMF1vocJV3vU/RDx9vuOICY2XUjrRrR01UC0IDxCkCXd0RIbLBNOiwvZcSQCC2+NGOfcOLl1eS9NnwsJ6GVo+eDMNNDbiZRTNQPFA1VpAPcPTTOz+ZgMuNbthiLs6dbjFKTmbYjJc2lj0B4A3ttEiYC0MQLQvSCWTfTdFj9jlgkJtPrn6b9zWA6iZ6hiOh09EXTtu0KDJo1wnFsjZvdsxGhw5eAAyCNKpAxLy7UP/nWLOTYdUaCVi0HvDiv/uf0J96Gz0HEJZiVa02JH/yyltF5Z7KvVbObZHE4A2qceYujieCeZXezYro0n5FIbs+PBkHRP+rR56IvwAwK1J9OdxMCPpo0zLTDV0H+i4tlnI8gmPsmc2mWmeNPzpefOmEioffQyYtuSxMCzidl1onMCuah2kXsdCLZ5Il7fbK5aCUCos4bT9d3AIBkIIbq6Gsp4WRAiscVrat5ewaHJft0Rm2qmIgfuoeSLr/dhIXlAhAffixeWG2+ADDMgRKPyS+jwDANqtL+yqgxEFnqyedT2PK7JVhxFsMxdbM3vNiy+6nIroOEgysa1eMXWJ2fwvMBSpCtIRNFerwtS60pxGkTlSOMyrCyH+PMix1eU0meFJPViynhLo2fwhQ2zai+Pc1tjDjMANqP6Q==
  template:
    metadata:
      creationTimestamp: null
      name: airflow-redis-secret
      namespace: deeppharmgraph
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-processing-webserver
  namespace: deeppharmgraph
spec:
  hostnames:
  - dpg-processing.shamrock.systems
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: http-gateway
    namespace: kube-system
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: dpg-processing-airflow-webserver
      port: 8080
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: airflow-postgres
  namespace: deeppharmgraph
spec:
  instances: 1
  storage:
    size: 16Gi
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: airflow-redis-standalone
  namespace: deeppharmgraph
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.12
    imagePullPolicy: IfNotPresent
    redisSecret:
      key: password
      name: airflow-redis-secret
  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.44.0
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
