apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - ./namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.0/manifests/install.yaml
  - ./httproute.yaml

patches:
  - path: ./overlays/configmap.yaml
  - path: ./overlays/deployment.yaml
  - path: ./overlays/secret.keep.yaml
