apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ./githubcollectorgenerator.yaml
  - ./githubcollectorgenerator.setup.yaml

patches:
  - target:
      labelSelector: "app.kubernetes.io/component=grafana"
    patch: |-
      - op: add
        path: /metadata/annotations/config.kubernetes.io~1local-config
        value: "true"
  - target:
      kind: NetworkPolicy
      name: prometheus-k8s
      namespace: monitoring
    patch: |-
      - op: add
        path: /spec/ingress/-
        value:
          from:
            - podSelector:
                matchLabels:
                  app: grafana
            - namespaceSelector:
                matchLabels:
                  app.kubernetes.io/instance: in-cluster-grafana-operator
          ports:
            - port: 9090
              protocol: TCP
