apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: migration-network
  namespace: kubevirt
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "migration-bridge",
      "type": "ipvlan",
      "master": "eno2vlan310",
      "mode": "l2",
      "mtu": 9000,
      "ipam": {
        "type": "whereabouts",
        "range": "10.76.10.0/24",
        "range_start": "10.76.10.64"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: passt-network
  namespace: kubevirt
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "netbindingpasst",
      "plugins": [
        {
          "type": "kubevirt-passt-binding"
        }
      ]
    }
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
      - LiveMigration
      - NetworkBindingPlugins
    migrations:
      network: migration-network
    network:
      binding:
        passt:
          computeResourceOverhead:
            requests:
              memory: 500Mi
          migration: {}
          networkAttachmentDefinition: kubevirt/passt-network
          sidecarImage: quay.io/kubevirt/network-passt-binding:20250105_6b393ef5f3
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
