apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-env-configmap
  namespace: deeppharmgraph
data:
  AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "true"
  AUTH_KEYCLOAK_API_BASE_URL: https://dpg-auth.forging.cc/realms/master/protocol/
  AUTH_KEYCLOAK_SCOPE: openid
  AUTH_KEYCLOAK_ACCESS_TOKEN_URL: https://dpg-auth.forging.cc/realms/master/protocol/openid-connect/token
  AUTH_KEYCLOAK_AUTHORIZE_URL: https://dpg-auth.forging.cc/realms/master/protocol/openid-connect/auth
  AUTH_KEYCLOAK_JWKS_URL: https://dpg-auth.forging.cc/realms/master/protocol/openid-connect/certs
  AUTH_KEYCLOAK_CLIENT_ID: application-airflow
  AUTH_KEYCLOAK_AIRFLOW_BASE_URL: https://dpg-processing.forging.cc/
