apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deeppharmgraph

resources:
  - ./sealedsecret.yaml
  - ./redis.yaml
  - ./cluster.postgres.yaml
  - ./httproute.yaml

helmCharts: []
