apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reflector
resources:
  - ./namespace.yaml
  - https://github.com/emberstack/kubernetes-reflector/releases/download/v7.1.216/reflector.yaml
