[project]
name = "k8s-manifests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pre-commit>=4.0.1",
    "yamllint>=1.35.1",
]
