apiVersion: ceph.rook.io/v1
kind: CephClient
metadata:
  name: extnode-dandelion0
  namespace: rook-ceph
spec:
  caps:
    mon: "allow r"
    mds: "allow r, allow rw path=/"
    osd: "allow rw tag cephfs data=filesystem-erasure"
