apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/rook/rook/v1.13.1/deploy/examples/crds.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.13.1/deploy/examples/common.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.13.1/deploy/examples/operator.yaml
  - ./networkattachmentdefinition.yaml
  - ./cephcluster.yaml
  - ./deployment.tools.yaml
  - ./storage-replicated/
  - ./storage-erasure/
  - ./storage-filesystem/
  - ./cephobjectstore.yaml

patches:
  - path: overlays/operator.yaml
