apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/rook/rook/v1.13.3/deploy/examples/crds.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.13.3/deploy/examples/common.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.13.3/deploy/examples/operator.yaml
  - ./networkattachmentdefinition.yaml
  - ./cephcluster.yaml
  - ./deployment.tools.yaml
  - ./storage-replicated/
  - ./storage-erasure/
  - ./storage-filesystem/
  - ./storage-object/
  - ./httproute.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.13.3/deploy/examples/monitoring/service-monitor.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.13.3/deploy/examples/monitoring/exporter-service-monitor.yaml
  - ./grafanadashboard.yaml
  - ./cephclient.dandelion0.yaml

patches:
  - path: overlays/operator.yaml
