apiVersion: v1
kind: Service
metadata:
  labels:
    ipPool: metal-cephnet
  name: rook-nfs-lb
  namespace: rook-ceph
spec:
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 2049
  selector:
    ceph_nfs: rook-nfs
  type: LoadBalancer
