apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      volumes:
        - name: keycloak-config
          configMap:
            name: keycloak-config
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0
          args: ["start"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "password"
            - name: KC_HOSTNAME
              value: "id.dev.lan.shamrock.systems"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              valueFrom:
                {secretKeyRef: {name: keycloak-postgres-app, key: jdbc-uri}}
            - name: KC_DB_USERNAME
              valueFrom:
                {secretKeyRef: {name: keycloak-postgres-app, key: username}}
            - name: KC_DB_PASSWORD
              valueFrom:
                {secretKeyRef: {name: keycloak-postgres-app, key: password}}
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
      initContainers:
        - name: keycloak-config-cli
          restartPolicy: Always
          image: docker.io/adorsys/keycloak-config-cli:5.10.0-23.0.1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: json-log
            - name: KEYCLOAK_URL
              value: http://localhost:8080
            - name: KEYCLOAK_LOGINREALM
              value: master
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "password"
            - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
              value: "true"
            - name: IMPORT_FILES_LOCATIONS
              value: /config/*
            - name: IMPORT_VARSUBSTITUTION_ENABLED
              value: "true"
          volumeMounts:
            - name: keycloak-config
              mountPath: /config
              readOnly: true
          command:
            - bash
            - -c
            - |-
              #!/usr/bin/env bash

              set -o errexit
              set -o pipefail
              set -o nounset

              while true
              do
                echo '{"message": "Running keycloak-config-cli"}'
                java $JAVA_OPTS -jar /app/keycloak-config-cli.jar
                sleep 1m
              done
      restartPolicy: Always
