apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/whereabouts/v0.8.0/doc/crds/daemonset-install.yaml
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/whereabouts/v0.8.0/doc/crds/whereabouts.cni.cncf.io_ippools.yaml
  - https://raw.githubusercontent.com/k8snetworkplumbingwg/whereabouts/v0.8.0/doc/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml

images:
  - name: ghcr.io/k8snetworkplumbingwg/whereabouts
    newTag: v0.8.0
