---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    KEYCLOAK_ADMIN: AgCufzV4A7udIKqoCaI38I+LIbjQn11T44oEInZ7fJxF4K95fc4xqgkMgK6lp2Ktb79QRCRx2ffXhuSbEcheeEKJfQEZye5HA8VdDNdcRE5djoj9ffBmmVRFTEkT3p0gF3KjlDn4morbtpcZw6Sdi55KJLmBCsYAVni5oX9lRSNsYtV9yXwX7LFpzkCYd9fhAQxPEdsqvAWjkMbhgPxb8gEPXVy8ZirKnQj24m5lQ41VMUnxaXNuCv4FlEujiWm9g/TW8LVhCtE8wrwzGAfAPZNsuwJ01itZOfdqLTCbDZP0ZIRqj1HF1NyUpSXsfFIQfhQEY0KfKM1/6wWX9M6Li807t8c3b2x78Ta2pBD9ESSNmoeTh/YF07NkJ4rPIDRAG/UN/mPS6C6cb07onFWfcB/oAybLuM//hV2VNgz85i/l0Pa9Fei+ROs9zjxPj24tDNE/UL39Q8CUdb+QCAFYfbymlEx4dO4Oj/9cqlCN810U1RNSVe4MWPmhJ0ULctu2aZL/KFLuB46i991sipwucw8ntybojKM1muvkb4HesTDRfp+nuD9aO/UeJrg1MnweDyhehdGdWlvgF27JBLIh/8kvXPXovMomC85Tz4a7qgAR1muJKtMAtk0G/wy/ob7IfLm/o5IaHlNg2M4XfHRqxv8JL5/iUBaUyF2oHst47UTNPdt4wXlqIjV1mPA4dT740fDnOStdSEEJGNszzwARA7DhvZ2gYeyoyYYZjqULUtc53w==
    KEYCLOAK_ADMIN_PASSWORD: AgCRoLnGPh3oTD4/+oHTnkS6iuKWMlvAaF/V3FGzY4qs1gWQrC26FoIAZcOZ8erhWbe9tg69B/gcG3FReBzGa6wFu9dhj7APBcXfm99qACXmebfe3qGEYrfpHRmTGrFYsFKtneeeAJiydybaPA6MP4pEfcexAHH76/ic9iYQNuvdO+lgOtGUsrzPuxKrbq7Vw87V6RK206s8A7IjvDzhga8/C/mzgnYWpOMQoYEvUiVw5Jm7pMouM5R57CFfHCFwlT9n/iDYzVyXjqp3zggk+ldhIzGck9th1idLBLpx52ISfwTilsD2+yMPM0XoXPjtAkktMUBLmhd1cjmuoUlmOZ9Lm7K142kDkE41TPwO3B6fx6xlgfKi2R2wNmhbfy3mfyUAaUS+yu570reTO8nT3xf0EegkZ/JOz65f9qCGNzyNTihJz57UWj9PKH/oeNx04vi0QrrCCTb43PL5CwEvwlxI67NvvHVpht8chSyrkCzWjTB8sN//prjwlw5eOn4s/efG/8dghzgJ8kFFZkzh52KODIes7DTv7K4AAainmtC3EbjM2hUvLisDd1PsBoJgZaA+XzHeVtIuVI8affc36rVMugha8jRZ9r7eVfdDEGxuttFymwFvvsX2AZcvXLHWZq21JF0DZOyb5ZpxNSs3nZP7KHmw5a3jpO56XdzeOabfxXBg7VAHCPEDM2LimXqOYo6i3fL6oZGNAhlNs0LeNp8ZRpaXju46Ig+w+9nKuqfzNw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin
      namespace: keycloak
