apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: object-erasure-selfsigned
  namespace: rook-ceph
spec:
  # Secret names are always required.
  secretName: object-erasure-selfsigned

  # secretTemplate is optional. If set, these annotations and labels will be
  # copied to the Secret named example-com-tls. These labels and annotations will
  # be re-reconciled if the Certificate's secretTemplate changes. secretTemplate
  # is also enforced, so relevant label and annotation changes on the Secret by a
  # third party will be overwriten by cert-manager to match the secretTemplate.
  # secretTemplate:
  #   annotations: {}
  #   labels: {}

  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - Shamrock Systems LLC
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: rook-ceph-rgw-object-erasure.rook-ceph.svc.cluster.local
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - rook-ceph-rgw-object-erasure.rook-ceph.svc.cluster.local
    - rook-ceph-rgw-object-erasure.rook-ceph.svc
    - rook-ceph-rgw-object-erasure.rook-ceph
    - rook-ceph-rgw-object-erasure
  # Issuer references are always required.
  issuerRef:
    name: selfsigned
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
