FROM quay.io/curl/curl:8.6.0 as build

USER root

ARG YQ_VERSION=v4.40.7
ARG YQ_BINARY=yq_linux_amd64

RUN curl -L "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY}" -o /usr/bin/yq && \
    chmod +x /usr/bin/yq
USER curl_user

COPY --chmod=755 --chown=curl_user:curl_group entrypoint.sh /entrypoint.sh
