apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: windows
  name: windows
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: domain-network
  namespace: kube-system
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "windows-domain",
      "type": "ipvlan",
      "master": "eno2vlan320",
      "mode": "l2",
      "mtu": 9000,
      "ipam": {
        "type": "whereabouts",
        "range": "10.76.20.0/24",
        "range_start": "10.76.20.64"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: domain-network
  namespace: windows
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "windows-domain",
      "type": "ipvlan",
      "master": "eno2vlan320",
      "mode": "l2",
      "mtu": 9000,
      "ipam": {
        "type": "whereabouts",
        "range": "10.76.20.0/24",
        "range_start": "10.76.20.64"
      }
    }
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-domain-0
  name: vmi-domain-0
  namespace: windows
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - bridge: {}
        name: domain
    resources:
      requests:
        memory: 1024M
  networks:
  - multus:
      default: true
      networkName: domain-network
    name: domain
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-domain-1
  name: vmi-domain-1
  namespace: windows
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - bridge: {}
        name: domain
    resources:
      requests:
        memory: 1024M
  networks:
  - multus:
      default: true
      networkName: domain-network
    name: domain
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
