apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: windows
  name: windows
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: domain-net
  namespace: windows
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "windows-domain",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "eno2vmbr0",
          "vlan": 320,
          "ipam": {}
        }
      ]
    }
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-domain-0
  name: vmi-domain-0
  namespace: windows
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - binding:
          name: passt
        name: cluster
      - bridge: {}
        name: domain
    resources:
      requests:
        memory: 1024M
  networks:
  - name: cluster
    pod: {}
  - multus:
      networkName: domain-net
    name: domain
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-domain-1
  name: vmi-domain-1
  namespace: windows
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - binding:
          name: passt
        name: cluster
      - bridge: {}
        name: domain
    resources:
      requests:
        memory: 1024M
  networks:
  - name: cluster
    pod: {}
  - multus:
      networkName: domain-net
    name: domain
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
