apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://metal-cd.shamrock.systems
  oidc.config: |
    name: Azure
    issuer: https://login.microsoftonline.com/7380c786-e737-424b-b1ff-fa4e2ff85ef4/v2.0
    clientID: 5e533d73-93ef-4bbb-9e08-4e65bf9090b6
    clientSecret: $oidc.azure.clientSecret
    requestedIDTokenClaims:
      groups:
        essential: true
    requestedScopes:
      - openid
      - profile
      - email
  admin.enabled: "false"
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, get, *, allow
    p, role:org-admin, repositories, get, *, allow
    p, role:org-admin, repositories, create, *, allow
    p, role:org-admin, repositories, update, *, allow
    p, role:org-admin, repositories, delete, *, allow
    g, "eae1814d-a39a-430b-b024-402432b8ab2e", role:org-admin
  scopes: '[groups, email]'
