apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: marin3r-system
  name: marin3r-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: marin3r-catalog
  namespace: marin3r-system
spec:
  displayName: MARIN3R Catalog
  image: quay.io/3scale/marin3r-catalog:latest
  publisher: Red Hat
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: marin3r
  namespace: marin3r-system
spec:
  channel: stable
  installPlanApproval: Automatic
  name: marin3r
  source: marin3r-catalog
  sourceNamespace: marin3r-system
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: marin3r-system
  namespace: marin3r-system
spec: {}
