apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kerria
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/ShamrockSystems/k8s-manifests.git
        revision: HEAD
        directories:
          - path: builds/cluster-metal/*
  template:
    metadata:
      name: 'in-cluster-{{.path.basename}}'
      namespace: argocd
    spec:
      project: "kerria"
      source:
        repoURL: https://github.com/ShamrockSystems/k8s-manifests.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: in-cluster
