apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kerria
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Kerria-managed Project

  sourceRepos:
    - https://github.com/ShamrockSystems/k8s-manifests.git

  destinations:
    - name: in-cluster
      namespace: "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
