apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: deeppharmgraph
  labels:
    app.kubernetes.io/name: keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
        - image: quay.io/keycloak/keycloak:23.0
          args:
            - start
            - --hostname=dpg-auth.forging.cc
            - --proxy=edge
          name: keycloak
          env:
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_ADDR
              valueFrom: {secretKeyRef: {name: keycloak-postgres-app, key: host}}
            - name: DB_PORT
              valueFrom: {secretKeyRef: {name: keycloak-postgres-app, key: port}}
            - name: DB_DATABASE
              valueFrom: {secretKeyRef: {name: keycloak-postgres-app, key: dbname}}
            - name: DB_USER
              valueFrom: {secretKeyRef: {name: keycloak-postgres-app, key: user}}
            - name: DB_PASSWORD
              valueFrom: {secretKeyRef: {name: keycloak-postgres-app, key: password}}
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "initial"
            - name: KC_PROXY
              value: "edge"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
      restartPolicy: Always
