apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: deeppharmgraph
  labels:
    app.kubernetes.io/name: keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
        - image: quay.io/keycloak/keycloak:23.0
          args: ["start"]
          name: keycloak
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "initial"
            - name: KC_HOSTNAME
              value: "dpg-auth.forging.cc"
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              valueFrom:
                {secretKeyRef: {name: keycloak-postgres-app, key: jdbc-uri}}
            - name: KC_DB_USERNAME
              valueFrom:
                {secretKeyRef: {name: keycloak-postgres-app, key: username}}
            - name: KC_DB_PASSWORD
              valueFrom:
                {secretKeyRef: {name: keycloak-postgres-app, key: password}}
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
      restartPolicy: Always
