apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-dashboard
  namespace: deeppharmgraph
spec:
  parentRefs:
    - name: http-gateway
      namespace: kube-system
  hostnames: [dpg-auth.shamrock.systems]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: dpg-authentication-keycloak
          port: 80
