apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: keycloakdb
  namespace: deeppharmgraph
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.5-0
  postgresVersion: 15
  instances:
    - replicas: 2
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.47-2
      configuration:
        - secret:
            name: pgo-backrest-repo-config
      global:
        repo1-path: /pgbackrest/postgres-operator/hippo-s3/repo1
      repos:
        - name: repo1
          s3:
            bucket: "pgo"
            endpoint: "s3-metal.shamrock.systems"
            region: "default"
