apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-ca-cert
  namespace: kube-system
spec:
  isCA: true
  # Secret names are always required.
  secretName: hubble-ca-tls

  # secretTemplate is optional. If set, these annotations and labels will be
  # copied to the Secret named example-com-tls. These labels and annotations will
  # be re-reconciled if the Certificate's secretTemplate changes. secretTemplate
  # is also enforced, so relevant label and annotation changes on the Secret by a
  # third party will be overwriten by cert-manager to match the secretTemplate.
  # secretTemplate:
  #   annotations: {}
  #   labels: {}

  duration: 87600h # 10 years (maximum allowed)
  renewBefore: 720h # Renew 30 days before expiry
  subject:
    organizations:
      - Shamrock Systems LLC
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: hubble-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # Issuer references are always required.
  issuerRef:
    name: selfsigned
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
