apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-operator
resources:
  - ./namespace.yaml
  - github.com/spotahome/redis-operator/manifests/kustomize/overlays/default?ref=v1.2.4
