apiVersion: kustomanager.shamrock.systems/v1alpha1
kind: KustomanagerLockfile

# Metadata for the repository this lockfile resides in
repo:
  url: https://github.com/ShamrockSystems/k8s-manifests.git
  revision: HEAD

# A list of clusters accesible from the Argo CD installation
# This information is used to populate the generate ApplicationSet resource.
clusters:
  - # The unique name of the cluster used by the CLI and internally
    name: metal
    # The directory that contains flat-directory Kustomization projects for the cluster
    directory: ./cluster-metal
    # The Argo CD destination cluster
    destination:
      # Either a server url OR
      server: https://kubernetes.default.svc
      # ... the name of a predefined Argo CD cluster
      name: default

# The directory where ApplicationSet resources are generated and managed
applicationsetDir: ./applicationsets

# The directory where all managed files are placed.
# This *should* be added to version control.
buildDir: ./builds

# Build lock information containing relevant build state
builds:
  - timestamp: <unix-timestamp>
    sourceHash: <some-sha-256-hash>
    sourceHashType: sha256
    sourcePath: ./cluster-metal/argocd
    buildHash: <some-sha-256-hash>
    buildHashType: sha256
    buildPath: ./builds/cluster-metal/argocd
    cluster: metal
