apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  keycloak.override: |
    rewrite name substring id.dev.lan.shamrock.systems keycloak.keycloak.svc.cluster.local
