apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxigraph-primary
  labels:
    app: oxigraph-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxigraph-primary
  template:
    metadata:
      labels:
        app: oxigraph-primary
    spec:
      volumes:
        - name: oxigraph-data
          persistentVolumeClaim:
            claimName: oxigraph-primary-pvc
      containers:
        - name: oxigraph
          image: ghcr.io/oxigraph/oxigraph:v0.3.22
          args:
            - --location
            - /data
            - serve
            - --bind
            - 0.0.0.0:7878
          ports:
            - containerPort: 7878
          volumeMounts:
            - mountPath: /data
              name: oxigraph-data
