apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oxigraph-primary-pvc
spec:
  resources:
    requests:
      storage: 32Gi
  storageClassName: filesystem-erasure
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oxigraph-ontology-pvc
spec:
  resources:
    requests:
      storage: 8Gi
  storageClassName: filesystem-erasure
  accessModes:
    - ReadWriteMany
