apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: ot-operators
  name: ot-operators
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ot-operators
  namespace: ot-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: redis-operator
  namespace: ot-operators
spec:
  channel: stable
  name: redis-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
