apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
spec:
  template:
    spec:
      containers:
        - name: immich-server
          env:
            - name: DB_DATABASE_NAME
              value: ""
              valueFrom:
                secretKeyRef: {name: immich-postgres-app, key: dbname}
            - name: DB_HOSTNAME
              value: ""
              valueFrom:
                secretKeyRef: {name: immich-postgres-superuser, key: host}
            - name: DB_PASSWORD
              value: ""
              valueFrom:
                secretKeyRef: {name: immich-postgres-superuser, key: password}
            - name: DB_USERNAME
              value: ""
              valueFrom:
                secretKeyRef: {name: immich-postgres-superuser, key: username}
