apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cosi
resources:
  - ./namespace.yaml
  - github.com/kubernetes-sigs/container-object-storage-interface-api?ref=v0.1.0
  - github.com/kubernetes-sigs/container-object-storage-interface-controller?ref=v0.1.2-alpha1
