apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: mc
  name: mc
---
apiVersion: v1
data:
  ALLOW_FLIGHT: "true"
  ALLOW_NETHER: "true"
  ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
  CF_EXCLUDE_MODS: "368398"
  CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/dawn-craft/files/5339411
  DIFFICULTY: hard
  ENABLE_COMMAND_BLOCK: "true"
  EULA: "true"
  FORCE_GAMEMODE: "false"
  FORGE_VERISON: 40.2.17
  GENERATE_STRUCTURES: "true"
  HARDCORE: "false"
  LEVEL: world
  LEVEL_TYPE: default
  MAX_BUILD_HEIGHT: "256"
  MAX_PLAYERS: "100"
  MAX_TICK_TIME: "-1"
  MEMORY: 16G
  MODE: survival
  MOTD: '☆*: .｡. o(≧▽≦)o .｡.:*☆'
  ONLINE_MODE: "true"
  OPS: GreenCappuccino
  OVERRIDE_SERVER_PROPERTIES: "true"
  PVP: "true"
  SERVER_NAME: DawnCraft
  SERVER_PORT: "25565"
  SNOOPER_ENABLED: "false"
  SPAWN_ANIMALS: "true"
  SPAWN_MONSTERS: "true"
  SPAWN_NPCS: "true"
  SPAWN_PROTECTION: "0"
  TYPE: AUTO_CURSEFORGE
  VERSION: 1.18.2
  VIEW_DISTANCE: "12"
kind: ConfigMap
metadata:
  name: mc-dawncraft-config
  namespace: mc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ipPool: metal-homenet
  name: mc-dawncraft
  namespace: mc
spec:
  ports:
  - port: 25565
    targetPort: 25565
  selector:
    app: mc-dawncraft
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mc-dawncraft
  namespace: mc
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mc-dawncraft
  serviceName: mc-dawncraft
  template:
    metadata:
      labels:
        app: mc-dawncraft
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: mc-dawncraft-config
        - secretRef:
            name: curseforge-secret
        image: itzg/minecraft-server:java17
        imagePullPolicy: Always
        name: mc-dawncraft
        ports:
        - containerPort: 25565
        readinessProbe:
          exec:
            command:
            - mc-monitor
            - status
            - --host
            - localhost
            - --port
            - "25565"
          failureThreshold: 18
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          limits:
            cpu: 4000m
            memory: 16Gi
          requests:
            cpu: 2000m
            memory: 8Gi
        volumeMounts:
        - mountPath: /data
          name: mc-dawncraft-storage
  volumeClaimTemplates:
  - metadata:
      name: mc-dawncraft-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: curseforge-secret
  namespace: mc
spec:
  encryptedData:
    CF_API_KEY: AgA69/xNpDlJwApRL4Gwsg673moDTt4d4+A03deXRP6e3yupHt+MT87p8pNYVilzyrJ9YIcJ3oeh5UQmd422NRpVZl4Q8AmJCmb66WVaWdRs+ropVz7UBfJ0Sc81bT9Y0/BkJ+NssVylnEHG5rDqEBSr5rTJJO5DKYjuO0sVzesFVY0KDGera1t2nlvknwh3WN0Znb5aYTPWFeKfpIvhe2JUeAwnAnlsdW7Kjrtu1ltYS+eqqw5ot97xe9vyexAdhtDmPPOymk574GkqAjTOd1G41faxYerNexAtg5xGOv1IkdhCYrsmdZSJE8K3D6o6OTT8m5ZRLRwx0V5nQdFWr1+dCh0YPpk2ZhBsikqDPnF2W8Vxf/2Zamub1mCkQUnFxfTbEZ72UmHaEJ3PEYEPQQFl0l2LH5Ue7P+5ezX77ceTSO3pUTnKQU4gPh1cm2+V8c5ce4pkJgplZB+d2rjohixyNk+SG/gO1tRpumsXjcjbSmvlSjRu8WmqiVtqK2CFqgMedL7S70gM125cmLCLyHSgum2ciOuvyRTbP40XFM5BFZiQKKSPwUE+sF22Grkt5PF12uHRHeORsuYUXz20/sITihSNvg87hYo14sNUfUh6K2fiLlGOJM+mkwLNV9TBPLBGh/cD2axQF/3Dgru7rOwp5Axnf26FcIGEOYJAYxctBfCLXGh9SYZxtFG+RnHpsQlSLeY0ausQm0X2TkqmB+epCop6b/Nh68MiLt9JA/f4zHaUF9xvzTw83k4Ntq/BCs5DBDGwo+twjJilAlI=
  template:
    metadata:
      creationTimestamp: null
      name: curseforge-secret
      namespace: mc
