apiVersion: v1
kind: Service
metadata:
  name: dpg-authentication-keycloak
  namespace: deeppharmgraph
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: keycloak
  name: keycloak
  namespace: deeppharmgraph
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
      - args:
        - start
        - --hostname=dpg-auth.forging.cc
        - --proxy=edge
        env:
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          valueFrom:
            secretKeyRef:
              key: host
              name: keycloak-postgres-app
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: keycloak-postgres-app
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              key: dbname
              name: keycloak-postgres-app
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: keycloak-postgres-app
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: keycloak-postgres-app
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: initial
        - name: KC_PROXY
          value: edge
        image: quay.io/keycloak/keycloak:23.0
        name: keycloak
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
      restartPolicy: Always
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-authentication
  namespace: deeppharmgraph
spec:
  hostnames:
  - dpg-auth.forging.cc
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: http-gateway
    namespace: kube-system
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: dpg-authentication-keycloak
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres
  namespace: deeppharmgraph
spec:
  instances: 1
  storage:
    size: 16Gi
