apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: cloudflared
  name: cloudflared
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cloudflared
  name: cloudflared
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      creationTimestamp: null
      labels:
        pod: cloudflared
    spec:
      containers:
      - args:
        - --token
        - $(CLOUDFLARED_TOKEN)
        command:
        - cloudflared
        - tunnel
        - --metrics
        - 0.0.0.0:2000
        - run
        env:
        - name: CLOUDFLARED_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: cloudflared
        image: cloudflare/cloudflared:latest
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /ready
            port: 2000
          initialDelaySeconds: 10
          periodSeconds: 10
        name: cloudflared
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared
  namespace: cloudflared
spec:
  encryptedData:
    token: AgC1v5yYG9V/lfi39/snv29pKG3M6lpSpP7FJQlE2lmmyWEda7KA2/8m7TZFBN+5a+NittkNjvXlMwEuo55b0YitWcKi4d8xsjIPRRNyhSDWJsDPEkLN50UC5bdy92QdtofgHY21EALxJhC6TLu8a3V1oNru5DWczgu2mLNDx5FEMKyUfC12cFuN9ViSgPT//8C5Ejqv8eUYa/7/gbgKwXFNrjBJpr6CEWaZuGmfXrlqYKnrGAZdrL5vC/S9NIH9gxWNDyLNWbqIriqLQaTUEaLSQA3KCyma9Jqw9qV5FsC7qjp5cWNrPFORZM8TxWHpACXs27QypWmX2VRYgtzpOd9JYbz6qtGNw3ecYNyIvgeid/8bC9zWEDGTTzNMzrmb2L/1RxHiKePHnubnHVb9ptKi+JEjwI1CjnfjP1u7Yu9Jjt5ZsKkT1+mJfOTPxSKeE10DMt6x671P4nap8QWCNc+oxYhNqWzdgU8O4zln/VgO044GzNAj0YMGPhWZh4zI0sbWltxu97z8vd5igItXfUcbeQQi24DvWRaxwvWrdDFHSeuAeJyuZnpBxZR82c+HJXkKgcqIdNZDjayV3DmbpxcHYkkafHMCW8LJ7JFpiPVVHzCL18bZAQKsTbDgRUBjCUV42D3jjCF4ZUVwkIw0rlCD1K8VrhkGbp4P5J+4Ju5I3tCg36h7GEVsCOXLETCLZ7p1u/ayNL7XQ38H+W/RRQRp4POifDh+/g99p3a5uo6VrP+AeaiXjm+2+998N9lzVoWFIjYsXovuoF1KTrvKmKltbWZLVAU9C+7iHzGpFWvFJQXXYtV98anCZgI8c8WXDxJu44epAD9SkKnLekYfN7vVgI9uMH4DgWML8dgYQke/t1rW5M2oeAEvebLirpek74SFNWSItq2Bmq0tn8ni4VZeI8cMY9HDQPHDIHsVkedU4t6wJyAMooHA
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared
      namespace: cloudflared
