apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: curl-debug
  name: curl-debug
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: curl-debug
  template:
    metadata:
      labels:
        app.kubernetes.io/name: curl-debug
    spec:
      containers:
      - args:
        - infinity
        command:
        - sleep
        image: quay.io/curl/curl:latest
        name: curl
