FROM quay.io/curl/curl:8.6.0 as get

USER root

ARG YQ_VERSION=v4.40.7
ARG YQ_BINARY=yq_linux_amd64
ARG JB_VERSION=v0.5.1
ARG JB_BINARY=jb-linux-amd64
ARG GO_JSONNET_VERSION=v0.20.0
ARG GO_JSONNET_ARCHIVE=go-jsonnet_0.20.0_Linux_x86_64.tar.gz

RUN curl -L "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY}" -o /yq
RUN curl -L "https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/${JB_VERSION}/${JB_BINARY}" -o /jb
RUN curl -L "https://github.com/google/go-jsonnet/releases/download/${GO_JSONNET_VERSION}/${GO_JSONNET_ARCHIVE}" -o /jsonnet-archive
RUN tar -xvf /jsonnet-archive -C /

FROM docker.io/bitnami/git:2.43.0

COPY --chmod=755 --from=get /yq /usr/bin/yq
COPY --chmod=755 --from=get /jb /usr/bin/jb
COPY --chmod=755 --from=get /jsonnet /usr/bin/jsonnet
COPY --chmod=755 --from=get /jsonnet-deps /usr/bin/jsonnet-deps
COPY --chmod=755 --chown=1001:1001 entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "" ]
