apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClass
metadata:
  name: noobaa-default
driverName: noobaa.objectstorage.k8s.io
deletionPolicy: delete
parameters:
  placementPolicy: '{"tiers":[{"backingStores":["noobaa-default-backing-store"]}]}'
