apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "metal-homenet"
spec:
  blocks:
    - start: "192.168.0.80"
      stop: "192.168.0.89"
  serviceSelector:
    matchLabels:
      ipPool: metal-homenet
