apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cluster-bgp
  namespace: kube-system
spec:
  nodeSelector: {}
  bgpInstances:
    - name: as4199764547
      localASN: 4199764547
      localPort: 179
      peers:
        - name: as4199764548
          peerASN: 4199764548
          peerAddress: 10.83.86.20
          peerConfigRef:
            name: ext-peer-dandelion
