apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cluster-bgp
  namespace: kube-system
spec:
  nodeSelector: {}
  bgpInstances:
    - name: as64567
      localASN: 64567
      peers:
        - name: as64568
          peerASN: 64568
          peerAddress: 10.83.86.20
          peerConfigRef:
            name: ext-peer-dandelion
