apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argo-aoa.proc.kerria.dev/filter/syncOptions: "['ServerSideApply=false']"
resources:
  - ./ciliumloadbalancerpool.services.yaml
  - ./ciliumloadbalancerpool.home.yaml
  - ./certificate.yaml
  - ./gatewayclass.yaml
  - ./gateway.yaml
  - ./grafanadashboard.yaml
  - ./httproute.yaml

helmCharts:
  - releaseName: cilium
    namespace: kube-system
    name: cilium
    repo: https://helm.cilium.io
    version: 1.16.5
    valuesFile: values.cilium.yaml
    includeCRDs: true

patches:
  - target:
      kind: CronJob
    patch: |
      - op: replace
        path: /apiVersion
        value: batch/v1
  - path: overlays/deployment.yaml
