apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kerria
  namespace: argocd
spec:
  destination:
    name: in-cluster
  project: kerria
  source:
    repoURL: file:///mnt/argo-cd-manifests
    targetRevision: HEAD
    path: cluster-local/applicationset
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
