apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kerria
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Kerria-managed Project
  sourceRepos:
    - file:///mnt/argo-cd-manifests
  destinations:
    - name: in-cluster
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
