apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: dpg-keycloak-realm
  namespace: deeppharmgraph
spec:
  forProvider:
    realm: deeppharmgraph
    displayName: DeepPharmGraph Barrier
    displayNameHtml: <div class="kc-logo-text"><span>DeepPharmGraph Barrier</span></div>
    enabled: true
    registrationAllowed: false
    registrationEmailAsUsername: false
    rememberMe: true
    resetPasswordAllowed: true
  providerConfigRef:
    name: keycloak-config
