apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.13.3/cert-manager.yaml
  - ./sealedsecret.yaml
  - ./clusterissuer.yaml

patches:
  - target:
      kind: Deployment
      name: cert-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --enable-certificate-owner-ref
