---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBjlHBWpkfKtyZZ8ZfwtKibvoSrwUWNgsRDunAUZa3CUw1kg/e/kdgQ4z/Um+RPMLfuF5ID//QIohIHZ1zmDo4t7XbtoEjiUt4tvlAUu1llmcQU9p9rI3e9YiEhrRM3hrtzG9zfFmydd0/Saisr4EQFm81XVFHagJmmBi56e+AA2ISjPZORP/ZAoNzUw6VAlmd2NOOfEoNZBU4we+CCUVQaG9wnLzqfgN87+I68T3QdvH56nLyC++0MnCkV7sVPrF6mtgGZ+DTKnKZdajGlh07a/bWSsjtHUV+r/Jt11C7laWfLkPBn+DAYjcJGuF3nnPCokRa6OwKg43/B8jPT8sY6dpvR6hXvGpChVx6NqBwJeRj8ME9knueO/06dpGK9LhqtWxNpGh+f5Kv1mf2jcgSHrehT70Bdcppr73uxQu39HAx5eow9PcjrBsSblevvASiBBxWf2CUx2xePaBoVR4/VDD1hRgk6zn9fK92yUDEuwcf2yI5qwItxU0fmEldGH1mSFYiENzFqjD4hA1DN0Ep4T3EnYizByWTo9rYsnUUHShjM7UCh0fJBOTzjsXFzK7rs2bTq1Bm90VlOcdVOPUDIf1doxkxBqrbE1voS2SGUTCNM3yV5GXuFSSys+8w0oW/5VdGGqLvnV609tLPLr5u2WcJ5xRt9EHdcKKaBmt/gB06tcZ4ZjSZA7sWW8U3cOQIvkXB6vIbsv+AspavK5me4dM+eroQoeTC6Ern4/Q2WB9DSvtY0dpNR
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
