apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml

helmCharts:
  - name: crossplane
    namespace: crossplane-system
    releaseName: crossplane
    repo: https://charts.crossplane.io/stable
    valuesFile: values.crossplane.yaml
    version: 1.15.0
    includeCRDs: true
