---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-domain-0
  name: vmi-domain-0
  namespace: windows
spec:
  domain:
    devices:
      disks:
        - disk:
            bus: virtio
          name: containerdisk
        - disk:
            bus: virtio
          name: cloudinitdisk
      interfaces:
        - name: cluster
          binding:
            name: passt
        - name: domain
          bridge: {}
    resources:
      requests:
        memory: 1024M
  networks:
    - name: cluster
      pod: {}
    - name: domain
      multus:
        networkName: domain-net
  terminationGracePeriodSeconds: 0
  volumes:
    - containerDisk:
        image: kubevirt/fedora-cloud-container-disk-demo:latest
      name: containerdisk
    - name: cloudinitdisk
      cloudInitNoCloud:
        userData: |-
          #cloud-config
          password: fedora
          chpasswd: { expire: False }
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-domain-1
  name: vmi-domain-1
  namespace: windows
spec:
  domain:
    devices:
      disks:
        - disk:
            bus: virtio
          name: containerdisk
        - disk:
            bus: virtio
          name: cloudinitdisk
      interfaces:
        - name: cluster
          binding:
            name: passt
        - name: domain
          bridge: {}
    resources:
      requests:
        memory: 1024M
  networks:
    - name: cluster
      pod: {}
    - name: domain
      multus:
        networkName: domain-net
  terminationGracePeriodSeconds: 0
  volumes:
    - containerDisk:
        image: kubevirt/fedora-cloud-container-disk-demo:latest
      name: containerdisk
    - name: cloudinitdisk
      cloudInitNoCloud:
        userData: |-
          #cloud-config
          password: fedora
          chpasswd: { expire: False }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: domain-net
  namespace: windows
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "windows-domain",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "eno2vmbr0",
          "vlan": 320,
          "ipam": {}
        }
      ]
    }
