---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-domain-0
  name: vmi-domain-0
  namespace: windows
spec:
  domain:
    devices:
      disks:
        - disk:
            bus: virtio
          name: containerdisk
        - disk:
            bus: virtio
          name: cloudinitdisk
      interfaces:
        - bridge: {}
          name: domain
    resources:
      requests:
        memory: 1024M
  networks:
    - name: domain
      multus:
        default: true
        networkName: domain-network
  terminationGracePeriodSeconds: 0
  volumes:
    - containerDisk:
        image: kubevirt/fedora-cloud-container-disk-demo:latest
      name: containerdisk
    - name: cloudinitdisk
      cloudInitNoCloud:
        userData: |-
          #cloud-config
          password: fedora
          chpasswd: { expire: False }
---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-domain-1
  name: vmi-domain-1
  namespace: windows
spec:
  domain:
    devices:
      disks:
        - disk:
            bus: virtio
          name: containerdisk
        - disk:
            bus: virtio
          name: cloudinitdisk
      interfaces:
        - bridge: {}
          name: domain
    resources:
      requests:
        memory: 1024M
  networks:
    - name: domain
      multus:
        default: true
        networkName: domain-network
  terminationGracePeriodSeconds: 0
  volumes:
    - containerDisk:
        image: kubevirt/fedora-cloud-container-disk-demo:latest
      name: containerdisk
    - name: cloudinitdisk
      cloudInitNoCloud:
        userData: |-
          #cloud-config
          password: fedora
          chpasswd: { expire: False }
