apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - ./namespace.yaml
  - ./cluster.postgres.yaml
  - ./redis.yaml
  - ./persistentvolumeclaim.yaml
  - ./httproute.yaml

helmCharts:
  - name: immich
    namespace: immich
    releaseName: immich
    repo: https://immich-app.github.io/immich-charts
    valuesFile: values.immich.yaml
    version: 0.4.0
