apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: immich
spec:
  storageClassName: filesystem-erasure
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Ti
  volumeMode: Filesystem
