apiVersion: v1
data:
  DP_MACVTAP_CONF: |
    [ {
        "name" : "ceph-multus-net",
        "lowerDevice" : "bond0",
        "mode": "bridge",
        "capacity" : 50
    } ]
kind: ConfigMap
metadata:
  name: macvtap-deviceplugin-config
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: macvtap-cni
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: macvtap-cni
  template:
    metadata:
      labels:
        name: macvtap-cni
    spec:
      containers:
      - command:
        - /macvtap-deviceplugin
        - -v
        - "3"
        - -logtostderr
        envFrom:
        - configMapRef:
            name: macvtap-deviceplugin-config
        image: quay.io/kubevirt/macvtap-cni:latest
        imagePullPolicy: Always
        name: macvtap-cni
        resources:
          requests:
            cpu: 60m
            memory: 30Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kubelet/device-plugins
          name: deviceplugin
      hostNetwork: true
      hostPID: true
      initContainers:
      - command:
        - cp
        - /macvtap-cni
        - /host/opt/cni/bin/macvtap
        image: quay.io/kubevirt/macvtap-cni:latest
        imagePullPolicy: Always
        name: install-cni
        resources:
          requests:
            cpu: 10m
            memory: 15Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host/opt/cni/bin
          mountPropagation: Bidirectional
          name: cni
      priorityClassName: system-node-critical
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
        name: deviceplugin
      - hostPath:
          path: /opt/cni/bin
        name: cni
