---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: curseforge-secret
  namespace: mc
spec:
  encryptedData:
    CF_API_KEY: AgA69/xNpDlJwApRL4Gwsg673moDTt4d4+A03deXRP6e3yupHt+MT87p8pNYVilzyrJ9YIcJ3oeh5UQmd422NRpVZl4Q8AmJCmb66WVaWdRs+ropVz7UBfJ0Sc81bT9Y0/BkJ+NssVylnEHG5rDqEBSr5rTJJO5DKYjuO0sVzesFVY0KDGera1t2nlvknwh3WN0Znb5aYTPWFeKfpIvhe2JUeAwnAnlsdW7Kjrtu1ltYS+eqqw5ot97xe9vyexAdhtDmPPOymk574GkqAjTOd1G41faxYerNexAtg5xGOv1IkdhCYrsmdZSJE8K3D6o6OTT8m5ZRLRwx0V5nQdFWr1+dCh0YPpk2ZhBsikqDPnF2W8Vxf/2Zamub1mCkQUnFxfTbEZ72UmHaEJ3PEYEPQQFl0l2LH5Ue7P+5ezX77ceTSO3pUTnKQU4gPh1cm2+V8c5ce4pkJgplZB+d2rjohixyNk+SG/gO1tRpumsXjcjbSmvlSjRu8WmqiVtqK2CFqgMedL7S70gM125cmLCLyHSgum2ciOuvyRTbP40XFM5BFZiQKKSPwUE+sF22Grkt5PF12uHRHeORsuYUXz20/sITihSNvg87hYo14sNUfUh6K2fiLlGOJM+mkwLNV9TBPLBGh/cD2axQF/3Dgru7rOwp5Axnf26FcIGEOYJAYxctBfCLXGh9SYZxtFG+RnHpsQlSLeY0ausQm0X2TkqmB+epCop6b/Nh68MiLt9JA/f4zHaUF9xvzTw83k4Ntq/BCs5DBDGwo+twjJilAlI=
  template:
    metadata:
      creationTimestamp: null
      name: curseforge-secret
      namespace: mc
