apiVersion: v1
kind: Service
metadata:
  name: mc-dawncraft
  namespace: mc
  labels:
    ipPool: metal-homenet
spec:
  type: LoadBalancer
  selector:
    app: mc-dawncraft
  ports:
    - port: 25565
      targetPort: 25565
