apiVersion: v1
kind: Service
metadata:
  name: mc-dawncraft
  namespace: mc
spec:
  type: NodePort
  selector:
    app: mc-dawncraft
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 32767
