apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubble-relay
  namespace: kube-system
spec:
  template:
    spec:
      volumes:
        - name: tls
          projected:
            sources:
              - secret:
                  items:
                    - key: tls.crt
                      path: client.crt
                    - key: tls.key
                      path: client.key
                    - key: ca.crt
                      path: hubble-client-ca.crt
                  name: hubble-relay-client-certs
              - secret:
                  items:
                    - key: ca.crt
                      path: hubble-server-ca.crt
                  name: hubble-server-certs
