apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: migration-network
  namespace: kubevirt
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "migration-bridge",
      "type": "ipvlan",
      "master": "eth1",
      "mode": "l2",
      "mtu": 9000,
      "ipam": {
        "type": "whereabouts",
        "range": "10.76.10.10/24",
        "range_start": "10.76.10.64",
        "node_slice_size": "/22"
      }
    }
