apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deeppharmgraph

resources:
  - ./postgres
  - ./xcom
  - ./secret.webserver.yaml
  - ./secret.fernet.yaml
  - ./secret.env.yaml
  - ./configmap.web.yaml
  - ./configmap.env.yaml
  - ./persistentvolume.yaml
  - ./persistentvolumeclaim.yaml
  - ./httproute.yaml

helmCharts:
  - releaseName: dpg-airflow
    namespace: deeppharmgraph
    name: airflow
    repo: https://airflow.apache.org
    version: 1.13.1
    valuesFile: values.airflow.yaml
