apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deeppharmgraph

resources:
  - ./secret.airflow.yaml
  - ./persistentvolumeclaim.yaml
  - ./persistentvolume.yaml
  - ./configmap.yaml
  - ./cluster.postgres.yaml
  - ./httproute.yaml

helmCharts:
  - releaseName: dpg-processing-airflow
    namespace: deeppharmgraph
    name: airflow
    repo: https://airflow-helm.github.io/charts
    version: 8.8.0
    valuesFile: values.airflow.yaml
