kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dags-host-ro
  namespace: deeppharmgraph
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 32Gi
