apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./objectbucketclaim.yaml

helmCharts:
  - releaseName: loki
    namespace: loki
    name: loki
    repo: https://grafana.github.io/helm-charts
    version: 5.42.2
    valuesFile: values.loki.yaml
