name: Build Generators

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-githubcollectorgenerator:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: githubcollectorgenerator
          tags: latest ${{ github.sha }}
          context: ./generators/githubcollectorgenerator
          containerfiles: |
            ./generators/githubcollectorgenerator/Containerfile

      - name: Log in to GitHub Container Registry
        id: login-ghcr
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/shamrocksystems

  build-jsonnetgenerator:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: jsonnetgenerator
          tags: latest ${{ github.sha }}
          context: ./generators/jsonnetgenerator
          containerfiles: |
            ./generators/jsonnetgenerator/Containerfile

      - name: Log in to GitHub Container Registry
        id: login-ghcr
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/shamrocksystems

  build-noobaagenerator:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: noobaagenerator
          tags: latest ${{ github.sha }}
          context: ./generators/noobaagenerator
          containerfiles: |
            ./generators/noobaagenerator/Containerfile

      - name: Log in to GitHub Container Registry
        id: login-ghcr
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/shamrocksystems
